dataset_path = "data/subset_movie_dataset-id-pc-yr.pt"
ratings_path = "data/ratings_subset.csv"
device = "cpu"
normalization_divisor = 10.0

hidden_size = 64
embedding_dim = 32
encoder_num_layers = 2
num_attention_heads = 4
num_self_attention_blocks = 1
num_cross_attention_blocks = 1
learning_rate = 0.001

context_size = 64
target_size = 8
epochs = 3
steps_per_epoch = 100
